version: '3'

services:
  investment:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"