version: '3'

services:
  investment:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mysql

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: investment
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306