server:
  port: 8081
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update
    showSql: true
    open-in-view: false
    properties:
      javax.persistence.query.timeout: 10000
      #hibernate.dialect: org.hibernate.dialect.MariaDBDialect
      org.hibernate.envers.audit_table_suffix: _history
      hibernate:
        format_sql: true
        ddl-auto: update
        connection:
          charset: utf8
          useUnicode: true
    defer-datasource-initialization: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.security: TRACE
    org.hibernate:
      SQL: DEBUG
      stat: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    jdbc: INFO
    jdbc.sqltiming: DEBUG
    jdbc.resultsettable: DEBUG