server:
  port: 5000
spring:
  redis:
    host: redis
    port: 6379
    database: 0
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: true
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:mysql://mysql:3306/investment?useSSL=false
#    useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#    initialization-mode: always
#    platform: mysql
  #    driver-class-name: org.h2.Driver
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties.hibernate.hbm2ddl.auto: update
    showSql: true
    open-in-view: false
    properties:
      javax.persistence.query.timeout: 10000
      org.hibernate.envers.audit_table_suffix: _history
      hibernate:
        format_sql: true
        ddl-auto: update
        connection:
          charset: utf8
          useUnicode: true
    defer-datasource-initialization: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.security: TRACE
    org.hibernate:
      SQL: DEBUG
      stat: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    jdbc: INFO
    jdbc.sqltiming: DEBUG
    jdbc.resultsettable: DEBUG