spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
    database: 0
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update
    showSql: true
    open-in-view: false
    properties:
      javax.persistence.query.timeout: 10000
      org.hibernate.envers.audit_table_suffix: _history
      hibernate:
        format_sql: true
        ddl-auto: update
        connection:
          charset: utf8
          useUnicode: true
    defer-datasource-initialization: true